apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-gin-crud
  namespace: {{ .Values.namespace }}
  labels:
    name: golang-gin-crud
spec:
  replicas: {{ .Values.golang_gin-crud_replicas }}
  selector:
    matchLabels:
      app: golang-gin-crud
  template:
    metadata:
      labels:
        app: golang-gin-crud
    spec:
      automountServiceAccountToken: true
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: name
                      operator: In
                      values:
                        - golang-gin-crud
                topologyKey: kubernetes.io/hostname
              weight: 100
      containers:
        - name: golang-gin-crud
          imagePullPolicy: IfNotPresent
          image: {{ .Values.golang_gin-crud_image_tag }}
          ports:
            - containerPort: 9090
          resources:
            requests:
              memory: {{ .Values.golang_gin-crud_requests_memory }}
              cpu: {{ .Values.golang_gin-crud_requests_cpu }}
            limits:
              memory: {{ .Values.golang_gin-crud_limits_memory }}
          command:
            - ./crud-webapp
      dnsPolicy: {{ .Values.golang_gin-crud_dns_policy }}
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 60
      nodeSelector:
        {{ .Values.golang_gin-crud_nodeselector }}: ""
