apiVersion: v1
kind: Service
metadata:
  name: golang-gin-crud
  namespace: '{{ .Values.namespace }}'
  labels:
    name: golang-gin-crud
spec:
  ports:
    - port: 80
      targetPort: 9090
      protocol: TCP
  selector:
    app: golang-gin-crud
  type: ClusterIP
