apiVersion: apps/v1
kind: Deployment
metadata:
  {{ if .Values.devstack_label }}
  annotations:
    janitor/ttl: "{{ .Values.ttl }}"
  {{ end }}
  {{ if .Values.devstack_label }}
  name: golang-sqs-{{ .Values.devstack_label }}
  {{ else }}
  name: golang-sqs
  {{ end }}
  namespace: {{ .Values.namespace }}
  labels:
    {{ if .Values.devstack_label }}
    name: golang-sqs-{{ .Values.devstack_label }}
    {{ else }}
    name: golang-sqs
    {{ end }}
spec:
  replicas: {{ .Values.golang_sqs_cli_replicas }}
  selector:
    matchLabels:
      {{ if .Values.devstack_label }}
      name: golang-sqs-{{ .Values.devstack_label }}
      {{ else }}
      name: golang-sqs
      {{ end }}
  template:
    metadata:
      labels:
        {{ if .Values.devstack_label }}
        name: golang-sqs-{{ .Values.devstack_label }}
        {{ else }}
        name: golang-sqs
        {{ end }}
    spec:
      automountServiceAccountToken: true
      containers:
        {{ if .Values.devstack_label }}
        - env:
            QUEUE_NAME: welcome-email-queue-{{ .Values.devstack_label }}
          name: golang-sqs-{{ .Values.devstack_label }}
        {{ else }}
        - name: golang-sqs
        {{ end }}
          imagePullPolicy: IfNotPresent
          image: razorpay/devstack:{{ .Values.image }}
          ports:
            - containerPort: 9090
          resources:
            requests:
              memory: {{ .Values.golang_sqs_cli_requests_memory }}
              cpu: {{ .Values.golang_sqs_cli_requests_cpu }}
            limits:
              memory: {{ .Values.golang_sqs_cli_limits_memory }}
          command:
            - ./crud-webapp
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 60
      nodeSelector:
        {{ .Values.golang_sqs_cli_nodeselector }}: ""
