#creation of namespace not required when running helmfile with devstack label as the namespace is already created
{{ if not .Values.devstack_label }}
{{- if .Values.create_ns }}
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: {{ .Values.namespace }}
  name: {{ .Values.namespace }}
spec:
  finalizers:
    - kubernetes
{{- end }}
{{ end }}

