apiVersion: v1
kind: ConfigMap
data:
  app.yaml: |
    queue:
      q1:
        name: sqs_{{ .Values.devstack_label }}
        secretKey: SQS_QUEUE_NAME
    updateSecret: true
    kubeSecret: sqs-{{ .Values.devstack_label }}
    namespace: demo
    provider: localstack
    enableEndpointPrefix: false
metadata:
  labels:
    app: sqs-{{ .Values.name }}-{{ .Values.devstack_label }}
  name: sqs-{{ .Values.name }}-{{ .Values.devstack_label }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "2"
  namespace: sqs-configurator
