name: SQS Configurator
on:
  push:
    paths:
      - 'hooks/sqs_configurator/**'

jobs:
  sqsc:
    runs-on: ubuntu-latest
    name: Build SQS configurator image
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.PUBLIC_DOCKER_USERNAME }}
          password: ${{ secrets.PUBLIC_DOCKER_PASSWORD }}
        # always uses a single image ,the changes are overridden
        # to-do versioning of the builds in case required
      - name: build configurator
        uses: docker/build-push-action@v2
        with:
          tags: razorpay/devstack:sqsc
          push: true
          file: ./hooks/sqs_configurator/Dockerfile
